services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: waiter
      POSTGRES_PASSWORD: password
      POSTGRES_DB: waiter_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://waiter:password@db:5432/waiter_db

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata:
